config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'
  get '/home', to: 'businesses#index'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :reviews, only: [:index]

  resources :businesses, only: [:show, :new, :create] do
    collection do
      get 'search'
    end
    resources :reviews, only: [:new, :create]
  end

  resources :users, only: [:create, :show]
  get 'ui(/:action)', controller: 'ui'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/business.rb
class Business < ActiveRecord::Base
  has_many :reviews, -> { order(created_at: :desc) }
  belongs_to :creator, class_name: "User", foreign_key: "user_id"

  validates_presence_of :name, :address, :city, :state, :zip_code, :phone_number

  def self.search_by_name(name)
    return [] if name.blank?
    Business.where("LOWER(NAME) LIKE ?", "%#{name.downcase}%")
  end

  def self.order_by_rating(businesses)
    businesses.order("rating DESC NULLS LAST")
  end

  def update_rating
    average = reviews.average(:rating).round(1)
    update(rating: average)
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :business
  belongs_to :user
  validates_presence_of :body, :rating
  validates :rating, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 0,
    less_than_or_equal_to: 5
  }

  after_save :update_business_rating

  def preview
    body.truncate_words(30)
  end

  private

  def update_business_rating
    business.update_rating
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :reviews, -> { order(created_at: :desc) }
  validates_presence_of :first_name, :last_name, :email
  validates_uniqueness_of :email

  def display_name
    "#{first_name.capitalize} #{last_name[0].capitalize}."
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :logged_in?, :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to do that."
      redirect_to login_path
    end
  end
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :require_user

  def index
    @businesses = Business.order_by_rating(Business.all)
  end

  def show
    @business = Business.find(params[:id])
  end

  def new
    @business = Business.new
  end

  def create
    @business = Business.new(business_params)
    @business.creator = current_user

    if @business.save
      flash[:success] = "Your business was created. Write a review!"
      redirect_to business_path(@business)
    else
      render :new
    end
  end

  def search
    results = Business.search_by_name(params[:search_term])
    @businesses = Business.order_by_rating(results)
  end

  private

  def business_params
    params.require(:business).permit(:name, :address, :city, :state, :zip_code, :phone_number)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :require_user

  def index
    @reviews = Review.all.order(created_at: :desc)
  end

  def new
    @review = Review.new
    @business = Business.find(params[:business_id])
  end

  def create
    @business = Business.find(params[:business_id])
    @review = @business.reviews.build(review_params)
    @review.user = current_user

    if @review.save
      flash[:success] = "Your review was created."
      redirect_to business_path(@business)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to home_path if logged_in?
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = "Welcome #{user.first_name}! You are logged in."
      redirect_to home_path
    else
      flash[:danger] = "Invalid email or password. Please try again."
      redirect_to login_path
    end
  end

  def destroy
    flash[:success] = "You have logged out."
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/ui_controller.rb
class UiController < ApplicationController
  before_filter do
    redirect_to :root if Rails.env.production?
  end

  layout "application"

  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, only: [:show]

  def new
    redirect_to home_path if logged_in?
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = "Account created. Please log in."
      redirect_to login_path
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def display_month_year(date)
    date.strftime("%B %Y")
  end

  def display_date(date)
    date.strftime("%m/%d/%Y")
  end

  def options_for_rating
    ["Choose Rating"] + (1..5).map { |n| [pluralize(n, "Star"), n] }
  end

  def rating_class(rating)
    return 0 if rating.nil?
    rating = ((rating * 2).round / 2.0).to_s
    class_name = "rating-#{rating[0]}"
    class_name += "-half" if rating.end_with?('.5')
    class_name
  end
end

app/views/businesses/_business.html.haml
%li
  .row
    .col-md-8
      %h4
        = (idx + 1).to_s + "."
        = link_to business.name, business_path(business)
      .rating-small{ class: rating_class(business.rating) }
      %span.ml-1
        = pluralize(business.reviews.count, "review")
    .col-md-4
      %address
        = render 'shared/address', obj: business
  - if business.reviews.any?
    %p
      = business.reviews.last.preview
      = link_to "read more", business_path(business)
  - else
    %p No reviews yet.

app/views/businesses/index.html.haml
%section.content-header
  .container
    %h3 Showing All Businesses
%section.content
  .container
    %ul
      - @businesses.each_with_index do |business, idx|
        %li
          .row
            .col-md-8
              %h4
                = (idx + 1).to_s + "."
                = link_to business.name, business_path(business)
              .rating-small{ class: rating_class(business.rating) }
              %span.ml-1
                = pluralize(business.reviews.count, "review")
            .col-md-4
              %address
                = render 'shared/address', obj: business
          - if business.reviews.any?
            %p
              = business.reviews.last.preview
              = link_to "read more", business_path(business)
          - else
            %p No reviews yet.

app/views/businesses/new.html.haml
%section.container.centered-form.mt-4
  %h3.mb-4 Add a New Business
  = render 'shared/errors', obj: @business
  = form_for @business do |f|
    %fieldset
      .form-group
        = f.text_field :name, class: "form-control", placeholder: "Business Name"
      .form-group
        = f.text_field :address, class: "form-control", placeholder: "Address"
      .form-group
        = f.text_field :city, class: "form-control", placeholder: "City"
      .form-group
        = f.text_field :state, class: "form-control", placeholder: "State"
      .form-group
        = f.text_field :zip_code, class: "form-control", placeholder: "Zip Code"
      .form-group
        = f.text_field :phone_number, class: "form-control", placeholder: "Phone Number"
      .form-group
        = f.submit "Add Business", class: "form-control btn register-button"

app/views/businesses/search.html.haml
%section.content-header
  .container
    %h3 Results for "#{params[:search_term]}"
    = link_to "Back", home_path
%section.content
  .container
    %ul
      - @businesses.each_with_index do |business, idx|
        = render 'business', business: business, idx: idx

app/views/businesses/show.html.haml
%section.content-header
  .container
    .row
      .col-md-9
        %h1= @business.name
        .rating-large{ class: rating_class(@business.rating) }
        %span.ml-1
          = pluralize(@business.reviews.count, "review")
        %address.mt-3
          = render 'shared/address', obj: @business
      .col-md-3.align-self-center
        = link_to "Write a Review", new_business_review_path(@business), class: "btn register-button"
%section.content
  .container
    %ul
      - @business.reviews.each do |review|
        %li
          .row
            .col-md-3
              %h5
                = link_to review.user.display_name, user_path(review.user)
              .user-review-count
                .user-review-logo
                %span.ml-1
                  = pluralize(review.user.reviews.count, "review")
            .col-md-9
              .rating-large{ class: rating_class(review.rating) }
              %span.review-date.ml-1= display_date(review.created_at)
              %p.pt-3= review.body

app/views/layouts/application.html.haml
!!! 5
%html(lang="en-US")
  %head
    %title MyYelp
    %meta(charset="UTF-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    = csrf_meta_tag
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
  %body
    %header
      = render "shared/header"
    %main
      = render "shared/messages"
      = yield

app/views/reviews/index.html.haml
%section.content-header
  .container
    %h3 Recent Reviews
%section.content
  .container
    %ul
      - @reviews.each do |review|
        %li
          .row
            .col-md-3
              %h4.mt-2
                = link_to review.business.name, business_path(review.business)
              .rating-small{ class: rating_class(review.business.rating) }
              %span.ml-1
                = pluralize(review.business.reviews.count, "review")
              %address.mt-1
                = render 'shared/address', obj: review.business
            .col-md-9
              .rating-small{ class: rating_class(review.rating) }
              %span.review-date.ml-1
                = display_date(review.created_at)
                by
                = link_to review.user.display_name, user_path(review.user)
              %p.pt-3= review.body

app/views/reviews/new.html.haml
%section.new-review.container.mt-4
  %h3 Write a Review
  %h5
    = link_to @business.name, business_path(@business.name)
  %address
    = render 'shared/address', obj: @business
  = render 'shared/errors', obj: @review
  = form_for [@business, @review] do |f|
    %fieldset
      .form-group
        = f.select :rating, options_for_rating, {}, { class: "form-control" }
      .form-group
        = f.text_area :body, class: "form-control", rows: "10", placeholder: "Your review"
      .form-group
        = f.submit "Post Review", class: "form-control btn register-button"

app/views/shared/_address.html.haml
#{obj.address}<br>
#{obj.city}, #{obj.state} #{obj.zip_code}<br>
#{number_to_phone(obj.phone_number, area_code: true)}

app/views/shared/_errors.html.haml
- if obj.errors.any?
  %div.alert.alert-danger.alert-dismissable.fade.show(role="alert")
    %button.close(data-dismiss="alert" aria-label="Close")
      %span(aria-hidden="true") &times;
    %p Please fix the following errors:
    %ul.ml-3
      - obj.errors.full_messages.each do |message|
        %li= message

app/views/shared/_header.html.haml
%nav
  %ul
    %li
      = link_to home_path do
        %img(src='/images/logo.png')
    - if logged_in?
      %li
        = form_tag search_businesses_path, method: 'get', class: "form-inline" do
          = text_field_tag :search_term, nil, placeholder: "Find", class: "form-control search-bar"
          = button_tag(type: "submit", class: "btn search-button") do
            %i.fa.fa-search
      %li
        = link_to "Businesses", home_path
      %li
        = link_to "Reviews", reviews_path
      %li.nav-item.dropdown
        %a.nav-link.dropdown-toggle(data-toggle="dropdown" href="#" role="button")
          = current_user.display_name
        .dropdown-menu
          = link_to "Add a New Business", new_business_path, class: "dropdown-item"
          = link_to "View Profile", user_path(current_user), class: "dropdown-item"
          = link_to "Log Out", logout_path, class: "dropdown-item"

app/views/shared/_messages.html.haml
- flash.keys.each do |key|
  %div.alert.alert-dismissable.fade.show(class="alert-#{key}" role="alert")
    %button.close(type="button" data-dismiss="alert" aria-label="Close")
      %span(aria-hidden="true") &times;
    %p= flash[key]

app/views/ui/business.html.haml
%section.content-header
  .container
    .row
      .col-md-9
        %h1 The French Laundry
        .rating-large.rating-4-half
        %span.ml-1 100 reviews
        %address.mt-3
          1234 Main St.<br>
          San Francisco, CA 94115<br>
          (415) 123-4567
      .col-md-3.align-self-center
        %button.btn.register-button(type="button") Write a Review
%section.content
  .container
    %ul
      %li
        .row
          .col-md-3
            %h5 <a href="">Jon Doe</a>
            .user-review-count
              .user-review-logo
              %span.ml-1 10 reviews
          .col-md-9
            .rating-small.rating-4
            %span.review-date.ml-1 5/20/17
            %p.pt-3 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin auctor efficitur elit, venenatis tincidunt nisl mattis id. Vestibulum sed lorem sapien. Sed consectetur nunc non purus bibendum, in lobortis nulla efficitur. Vivamus et metus elementum, accumsan ante dapibus, maximus ex. Aliquam convallis augue quis facilisis consequat. Curabitur non tincidunt ante. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum varius turpis quis semper luctus. Mauris fringilla suscipit ligula sit amet ornare. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla laoreet non est sed elementum. Sed eu pharetra magna, non cursus magna. In hendrerit tortor accumsan lorem scelerisque, commodo pretium dui ultrices. Vivamus lacinia mattis eros, et laoreet erat interdum id. Integer nec eros at est facilisis sollicitudin. Quisque pretium elementum aliquet.
      %li
        .row
          .col-md-3
            %h5 <a href="">Jon Doe</a>
            .user-review-count
              .user-review-logo
              %span.ml-1 10 reviews
          .col-md-9
            .rating-small.rating-3-half
            %span.review-date.ml-1 5/20/17
            %p.pt-3 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin auctor efficitur elit, venenatis tincidunt nisl mattis id. Vestibulum sed lorem sapien. Sed consectetur nunc non purus bibendum, in lobortis nulla efficitur. Vivamus et metus elementum, accumsan ante dapibus, maximus ex. Aliquam convallis augue quis facilisis consequat. Curabitur non tincidunt ante. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum varius turpis quis semper luctus. Mauris fringilla suscipit ligula sit amet ornare. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla laoreet non est sed elementum. Sed eu pharetra magna, non cursus magna. In hendrerit tortor accumsan lorem scelerisque, commodo pretium dui ultrices. Vivamus lacinia mattis eros, et laoreet erat interdum id. Integer nec eros at est facilisis sollicitudin. Quisque pretium elementum aliquet.
      %li
        .row
          .col-md-3
            %h5 <a href="">Jon Doe</a>
            .user-review-count
              .user-review-logo
              %span.ml-1 10 reviews
          .col-md-9
            .rating-small.rating-2
            %span.review-date.ml-1 5/20/17
            %p.pt-3 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin auctor efficitur elit, venenatis tincidunt nisl mattis id. Vestibulum sed lorem sapien. Sed consectetur nunc non purus bibendum, in lobortis nulla efficitur. Vivamus et metus elementum, accumsan ante dapibus, maximus ex. Aliquam convallis augue quis facilisis consequat. Curabitur non tincidunt ante. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum varius turpis quis semper luctus. Mauris fringilla suscipit ligula sit amet ornare. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla laoreet non est sed elementum. Sed eu pharetra magna, non cursus magna. In hendrerit tortor accumsan lorem scelerisque, commodo pretium dui ultrices. Vivamus lacinia mattis eros, et laoreet erat interdum id. Integer nec eros at est facilisis sollicitudin. Quisque pretium elementum aliquet.

app/views/ui/businesses.html.haml
%section.content-header
  .container
    %h3 Showing All Businesses
%section.content
  .container
    %ul
      %li
        .row
          .col-md-8
            %h4 1. <a href="">The French Laundry</a>
            .rating-small.rating-4
            %span.ml-1 100 reviews
          .col-md-4
            %address
              1234 Main St.<br>
              San Francisco, CA 94115<br>
              (415) 123-4567
        %p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque id convallis erat. Integer nisl nibh, tempus non enim eget, lacinia condimentum neque. Integer dictum maximus sem, at ullamcorper augue. Vivamus non metus arcu....<a href="">read more</a>
      %li
        .row
          .col-md-8
            %h4 2. <a href="">Saison</a>
            .rating-small.rating-3-half
            %span.ml-1 85 reviews
          .col-md-4
            %address
              1234 Main St.<br>
              San Francisco, CA 94115<br>
              (415) 123-4567
        %p It was just ok <a href="">read more</a>
      %li
        .row
          .col-md-8
            %h4 3. <a href="">Acquerello</a>
            .rating-small.rating-1
            %span.ml-1 20 reviews
          .col-md-4
            %address
              1234 Main St.<br>
              San Francisco, CA 94115<br>
              (415) 123-4567
        %p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque id convallis erat. Integer nisl nibh, tempus non enim eget, lacinia condimentum neque. Integer dictum maximus sem, at ullamcorper augue. Vivamus non metus arcu....<a href="">read more</a>

app/views/ui/index.html.haml
%ul.ml-5.mt-5
  - Dir.glob('app/views/ui/*.html.haml').sort.each do |file|
    - wireframe = File.basename(file,'.html.haml')
    -  unless wireframe == 'index' || wireframe.match(/^_/)
      %li= link_to wireframe.titleize, action: wireframe unless wireframe == 'index'

app/views/ui/login.html.haml
%section.container.centered-form.mt-4
  %h3 Log In to Yelp
  %p
    %small <strong>New to Yelp?</strong> <a href=''>Sign up</a>
  %form
    %fieldset
      .form-group
        %input.form-control(type='text' placeholder='Email')
      .form-group
        %input.form-control(type='text' placeholder='Password')
      .form-group
        %input.form-control.btn.register-button(type='submit' value='Log In')

app/views/ui/new_business.html.haml
%section.container.centered-form.mt-4
  %h3.mb-4 Add a New Business
  %form
    %fieldset
      .form-group
        %input.form-control(type='text' placeholder='Business Name')
      .form-group
        %input.form-control(type='text' placeholder='Address')
      .form-group
        %input.form-control(type='text' placeholder='City')
      .form-group
        %input.form-control(type='text' placeholder='State')
      .form-group
        %input.form-control(type='text' placeholder='Zip Code')
      .form-group
        %input.form-control(type='text' placeholder='Phone Number')
      .form-group
        %input.form-control.btn.register-button(type='submit' value='Add Business')

app/views/ui/new_review.html.haml
%section.new-review.container.mt-4
  %h3 Write a Review
  %h5 <a href="">The French Laundry</a>
  %address
    1234 Main St.<br>
    San Francisco, CA 94115<br>
    (415) 123-4567
  %form
    %fieldset
      .form-group
        %select#rating.form-control.w-25(type='text' placeholder='star rating')
          %option Rating
          %option 1 Star
          %option 2 Stars
          %option 3 Stars
          %option 4 Stars
          %option 5 Stars
      .form-group
        %textarea.form-control(placeholder='Your review' rows="10")
      .form-group
        %input.form-control.btn.register-button(type='submit' value='Post Review')

app/views/ui/reviews.html.haml
%section.content-header
  .container
    %h3 Recent Reviews
%section.content
  .container
    %ul
      %li
        .row
          .col-md-3
            %h4.mt-2 <a href="">The French Laundry</a>
            .rating-small.rating-4
            %span.ml-1 100 reviews
            %address
              1234 Main St.<br>
              San Francisco, CA 94115<br>
              (415) 123-4567
          .col-md-9
            .rating-small.rating-4
            %span.review-date.ml-1 9/28/17 by <a href="">Jon Doe</a>
            %p.pt-3 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin auctor efficitur elit, venenatis tincidunt nisl mattis id. Vestibulum sed lorem sapien. Sed consectetur nunc non purus bibendum, in lobortis nulla efficitur. Vivamus et metus elementum, accumsan ante dapibus, maximus ex. Aliquam convallis augue quis facilisis consequat. Curabitur non tincidunt ante. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum varius turpis quis semper luctus. Mauris fringilla suscipit ligula sit amet ornare. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla laoreet non est sed elementum. Sed eu pharetra magna, non cursus magna. In hendrerit tortor accumsan lorem scelerisque, commodo pretium dui ultrices. Vivamus lacinia mattis eros, et laoreet erat interdum id. Integer nec eros at est facilisis sollicitudin. Quisque pretium elementum aliquet.
      %li
        .row
          .col-md-3
            %h4.mt-2 <a href="">Saison</a>
            .rating-small.rating-4
            %span.ml-1 100 reviews
            %address
              1234 Main St.<br>
              San Francisco, CA 94115<br>
              (415) 123-4567
          .col-md-9
            .rating-small.rating-4
            %span.review-date.ml-1 8/20/17 by <a href="">Jane Smith</a>
            %p.pt-3 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin auctor efficitur elit, venenatis tincidunt nisl mattis id. Vestibulum sed lorem sapien. Sed consectetur nunc non purus bibendum, in lobortis nulla efficitur. Vivamus et metus elementum, accumsan ante dapibus, maximus ex. Aliquam convallis augue quis facilisis consequat. Curabitur non tincidunt ante. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum varius turpis quis semper luctus. Mauris fringilla suscipit ligula sit amet ornare. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla laoreet non est sed elementum. Sed eu pharetra magna, non cursus magna. In hendrerit tortor accumsan lorem scelerisque, commodo pretium dui ultrices. Vivamus lacinia mattis eros, et laoreet erat interdum id. Integer nec eros at est facilisis sollicitudin. Quisque pretium elementum aliquet.
      %li
        .row
          .col-md-3
            %h4.mt-2 <a href="">Acquerello</a>
            .rating-small.rating-4
            %span.ml-1 100 reviews
            %address
              1234 Main St.<br>
              San Francisco, CA 94115<br>
              (415) 123-4567
          .col-md-9
            .rating-small.rating-4
            %span.review-date.ml-1 7/20/17 by <a href="">Bob Jones</a>
            %p.pt-3 Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin auctor efficitur elit, venenatis tincidunt nisl mattis id. Vestibulum sed lorem sapien. Sed consectetur nunc non purus bibendum, in lobortis nulla efficitur. Vivamus et metus elementum, accumsan ante dapibus, maximus ex. Aliquam convallis augue quis facilisis consequat. Curabitur non tincidunt ante. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum varius turpis quis semper luctus. Mauris fringilla suscipit ligula sit amet ornare. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla laoreet non est sed elementum. Sed eu pharetra magna, non cursus magna. In hendrerit tortor accumsan lorem scelerisque, commodo pretium dui ultrices. Vivamus lacinia mattis eros, et laoreet erat interdum id. Integer nec eros at est facilisis sollicitudin. Quisque pretium elementum aliquet.

app/views/ui/signup.html.haml
%section.container.centered-form.mt-4
  %h3 Sign Up for Yelp
  %p
    %strong Connect with great local businesses
  %form
    %fieldset
      .form-row
        .form-group.col
          %input.form-control(type='text' placeholder='First Name')
        .form-group.col
          %input.form-control(type='text' placeholder='Last Name')
      .form-group
        %input.form-control(type='text' placeholder='Email')
      .form-group
        %input.form-control(type='text' placeholder='Password')
      .form-group
        %input.form-control.btn.register-button(type='submit' value='Sign Up')
  %p
    %small Already on Yelp? <a href=''>Log in</a>

app/views/users/new.html.haml
%section.container.centered-form.mt-4
  %h3 Sign Up for Yelp
  %p
    %strong Connect with great local businesses
  = form_for @user do |f|
    %fieldset
      .form-row
        .form-group.col
          = f.text_field :first_name, class: "form-control", placeholder: "First Name"
        .form-group.col
          = f.text_field :last_name, class: "form-control", placeholder: "Last Name"
      .form-group
        = f.email_field :email, class: "form-control", placeholder: "Email"
      .form-group
        = f.password_field :password, class: "form-control", placeholder: "Password"
      .form-group
        = f.submit "Sign up", class: "btn register-button form-control"
  %p
    %small
      Already on Yelp?
      = link_to "Log In", login_path

app/views/users/show.html.haml
%section.content-header
  .container
    %h1= @user.display_name
    .user-review-count
      .user-review-logo-large
      %span.ml-1
        = pluralize(@user.reviews.count, "review")
    %p.mt-1
      %strong Member Since
      #{display_month_year(@user.created_at)}
%section.content.user
  .container
    %h3 Reviews
    %ul
      - @user.reviews.each do |review|
        %li
          .row
            .col-md-3
              %h5
                = link_to review.business.name, business_path(review.business)
              .rating-small{ class: rating_class(review.business.rating) }
              %span.ml-1
                = pluralize(review.business.reviews.count, "review")
              %address
                = render 'shared/address', obj: review.business
            .col-md-9
              .rating-small{ class: rating_class(review.rating) }
              %span.review-date.ml-1= display_date(review.created_at)
              %p.pt-3= review.body